################################################################################
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
################################################################################

resampleFilter = "lanczos"
quality = 75
anchor = "smart"
