############################# English - Main Menu ########################
[[main]]
name = "Home"
url = "/"
weight = 1
[main.params]
bsicon = "house-fill"

############################# Footer Menu ########################
[[footer]]
name = "Tags"
url = "/tags/"
weight = 200
[footer.params]
bsicon = "tags-fill"

[[footer]]
name = "Home"
url = "/"
weight = 100
[footer.params]
bsicon = "house-fill"

[[footer]]
name = "Contact"
url = "/contact/"
weight = 900
[footer.params]
bsicon = "envelope-paper-fill"

### Footer submenus ###
[[configurations]]
name = "@davidsneighbour/browserslist-config"
url = "https://www.npmjs.com/package/@davidsneighbour/browserslist-config"
weight = 500
[[configurations]]
name = "@davidsneighbour/eslint-config"
url = "https://www.npmjs.com/package/@davidsneighbour/eslint-config"
weight = 300
[[configurations]]
name = "@davidsneighbour/config"
url = "https://www.npmjs.com/package/@davidsneighbour/config"
weight = 100

[[hugomodules]]
name = "Tags"
url = "/tags/"
weight = 200

[[projects]]
name = "Tags"
url = "/tags/"
weight = 200
