################################################################################
# see https://gohugo.io/getting-started/configuration/#configure-minify
################################################################################
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = true
minifyOutput = false

[tdewolff]

[tdewolff.css]
# deprecated in favour of precision
# decimals = -1
# prohibits using CSS3 syntax (such as exponents in numbers, or rgba( â†’ rgb(), might be incomplete
keepCSS2 = true
# number of significant digits to preserve for numbers, 0 means no trimming
precision = 10

[tdewolff.html]
# preserve all IE conditional comments such as <!--[if IE 6]><![endif]--> and
# <![if IE 6]><![endif]>, see https://msdn.microsoft.com/en-us/library/ms537512(v=vs.85).aspx#syntax
keepConditionalComments = true
# preserve default attribute values such as <script type="application/javascript">
keepDefaultAttrVals = true
# preserve html, head and body tags
keepDocumentTags = true
# preserve all end tags
keepEndTags = true
# preserve quotes around attribute values
keepQuotes = false
# preserve whitespace between inline tags but still collapse multiple whitespace characters into one
keepWhitespace = false
# preserve all comments
keepComments = false

[tdewolff.js]
# keeps variable names as they are and omits shortening variable names
keepVarNames = false
# number of significant digits to preserve for numbers, 0 means no trimming
precision = 10

[tdewolff.json]
# do not minify numbers if set to true, by default numbers will be minified
keepNumbers = false
# number of significant digits to preserve for numbers, 0 means no trimming
precision = 10

[tdewolff.svg]
# number of significant digits to preserve for numbers, 0 means no trimming
precision = 10

[tdewolff.xml]
# preserve whitespace between inline tags but still collapse multiple whitespace characters into one
keepWhitespace = false
