################################################################################
# see https://gohugo.io/getting-started/configuration/
################################################################################
baseURL = "http://192.168.1.201:1313/"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
footnoteReturnLinkContents = "^"
ignoreErrors = []
languageCode = "en-us"
linenos = true
paginate = 10
rssLimit = 10
summaryLength = 40
timeZone = "Asia/Bangkok"
title = "kollitsch.dev"
# hack: adding a crazy timeout to prevent hugo from... timing out...
timeout = 100000000000000
