################################################################################
# https://gohugo.io/getting-started/configuration/#configure-build
################################################################################
#useResourceCacheWhen = "never"

[buildStats]
enable = true          # default is false
disableClasses = false # default is false
disableIDs = false     # default is false
disableTags = false    # default is false

[[cachebusters]]
source = 'scss'
target = 'css'
