################################################################################
# see http://gohugo.io/templates/output-formats/
################################################################################

[Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[REDIR]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

[manifest]
mediaType = "application/manifest+json"
baseName = "manifest"
isPlainText = true
notAlternative = true
